@echo off
echo Запускаем сервер...
start "" cmd /k "node server.js"
echo Ожидаем пару секунд, чтобы сервер успел подняться...
timeout /t 2 >nul
echo Открываем страницу в браузере...
start "" http://localhost:8080/
